export const EVAM_VERSION = "1.0.0";

export const FIELD_CATALOG = Object.freeze({
  age: { label: "Idade", type: "number", unit: "anos", group: "Identificação mínima" },
  sex: { label: "Sexo registrado", type: "text", group: "Identificação mínima" },
  origin: { label: "Unidade de origem", type: "text", group: "Contexto regulatório" },
  recognitionTime: { label: "Reconhecimento da síndrome", type: "datetime-local", group: "Linha do tempo" },
  symptomOnset: { label: "Início dos sintomas", type: "datetime-local", group: "Linha do tempo" },
  lastKnownWell: { label: "Último momento bem (LKW)", type: "datetime-local", group: "Linha do tempo" },
  hoursSinceRecognition: { label: "Horas desde o reconhecimento", type: "number", unit: "h", step: "0.1", group: "Linha do tempo" },
  sbp: { label: "Pressão sistólica", type: "number", unit: "mmHg", group: "Estado atual" },
  dbp: { label: "Pressão diastólica", type: "number", unit: "mmHg", group: "Estado atual" },
  map: { label: "Pressão arterial média", type: "number", unit: "mmHg", group: "Estado atual" },
  heartRate: { label: "Frequência cardíaca", type: "number", unit: "bpm", group: "Estado atual" },
  respiratoryRate: { label: "Frequência respiratória", type: "number", unit: "irpm", group: "Estado atual" },
  spo2: { label: "SpO₂", type: "number", unit: "%", group: "Estado atual" },
  temperature: { label: "Temperatura", type: "number", unit: "°C", step: "0.1", group: "Estado atual" },
  gcs: { label: "Escala de Coma de Glasgow", type: "number", unit: "/15", group: "Estado atual" },
  oxygenSupport: { label: "Suporte de oxigênio/ventilatório", type: "text", group: "Suporte atual" },
  vasopressor: { label: "Vasopressor", type: "text", group: "Suporte atual" },
  lactate: { label: "Lactato", type: "number", unit: "mmol/L", step: "0.1", group: "Laboratório" },
  creatinine: { label: "Creatinina", type: "number", unit: "mg/dL", step: "0.01", group: "Laboratório" },
  bilirubin: { label: "Bilirrubina total", type: "number", unit: "mg/dL", step: "0.1", group: "Laboratório" },
  platelets: { label: "Plaquetas", type: "number", unit: "/mm³", group: "Laboratório" },
  inr: { label: "INR", type: "number", step: "0.01", group: "Laboratório" },
  troponin: { label: "Troponina", type: "text", group: "Laboratório" },
  ph: { label: "pH", type: "number", step: "0.01", group: "Laboratório" },
  pao2: { label: "PaO₂", type: "number", unit: "mmHg", group: "Laboratório" },
  fio2: { label: "FiO₂", type: "number", unit: "%", group: "Laboratório" },
  nihss: { label: "NIHSS", type: "number", unit: "pontos", group: "Neurológico" },
  pupilExam: { label: "Pupilas", type: "text", group: "Neurológico" },
  focalDeficit: { label: "Déficit focal", type: "text", group: "Neurológico" },
  ecg: { label: "ECG", type: "textarea", group: "Exames-chave" },
  imaging: { label: "Imagem relevante", type: "textarea", group: "Exames-chave" },
  injuryMechanism: { label: "Mecanismo do trauma", type: "textarea", group: "Trauma" },
  hemorrhage: { label: "Hemorragia ativa/suspeita", type: "text", group: "Trauma" },
  interventionNeeded: { label: "Intervenção tempo-dependente requerida", type: "textarea", group: "Necessidade resolutiva" },
  capabilityNeeded: { label: "Capacidade executora necessária", type: "textarea", group: "Necessidade resolutiva" },
  currentLimit: { label: "Limitação da unidade atual", type: "textarea", group: "Necessidade resolutiva" },
  clinicalQuestion: { label: "Questão regulatória", type: "textarea", group: "Síntese" },
  evolution: { label: "Evolução temporal relevante", type: "textarea", group: "Síntese" },
});

const common = ["age", "sex", "origin", "recognitionTime", "hoursSinceRecognition", "sbp", "dbp", "map", "heartRate", "respiratoryRate", "spo2", "gcs", "oxygenSupport", "vasopressor", "interventionNeeded", "capabilityNeeded", "currentLimit", "clinicalQuestion", "evolution"];

export const SCHEMA_TEMPLATES = Object.freeze([
  {
    id: "sepsis-biliary.emergency-gastro.v1",
    version: "1.0.0",
    specialty: "Emergência · Gastroenterologia · Cirurgia",
    syndrome: "Sepse biliar / colangite",
    title: "Sepse biliar com necessidade de controle de foco",
    purpose: "Regulação para unidade capaz de executar drenagem biliar/CPRE, com suporte intensivo quando indicado.",
    defaultIntervention: "Controle de foco biliar em janela clinicamente adequada.",
    defaultCapability: "Endoscopia biliar/CPRE ou drenagem alternativa + retaguarda de UTI e equipe executora disponível.",
    fields: [...common, "temperature", "lactate", "creatinine", "bilirubin", "platelets", "inr", "imaging"],
    required: ["age", "recognitionTime", "map", "lactate", "bilirubin", "interventionNeeded", "capabilityNeeded", "currentLimit"],
  },
  {
    id: "acute-coronary-syndrome.cardiology.v1",
    version: "1.0.0",
    specialty: "Emergência · Cardiologia · Hemodinâmica",
    syndrome: "Síndrome coronariana aguda",
    title: "Síndrome coronariana aguda com possível estratégia invasiva",
    purpose: "Organizar informação para matching com hemodinâmica e retaguarda cardiológica.",
    defaultIntervention: "Avaliação/estratégia de reperfusão ou abordagem invasiva conforme fenótipo e janela.",
    defaultCapability: "Hemodinâmica operacional + cardiologia/UTI coronariana conforme necessidade.",
    fields: [...common, "symptomOnset", "temperature", "lactate", "creatinine", "troponin", "ecg", "imaging"],
    required: ["age", "symptomOnset", "sbp", "spo2", "ecg", "troponin", "interventionNeeded", "capabilityNeeded"],
  },
  {
    id: "acute-ischemic-stroke.neurology.v1",
    version: "1.0.0",
    specialty: "Emergência · Neurologia · Neurorradiologia intervencionista",
    syndrome: "Acidente vascular cerebral agudo",
    title: "AVC agudo com avaliação para reperfusão/trombectomia",
    purpose: "Estruturar tempo, déficit, imagem e capacidade de reperfusão para regulação neurovascular.",
    defaultIntervention: "Avaliação imediata de elegibilidade para reperfusão e/ou trombectomia mecânica.",
    defaultCapability: "Neurologia vascular + neuroimagem + trombólise e/ou neurorradiologia intervencionista operacional.",
    fields: [...common, "symptomOnset", "lastKnownWell", "sbp", "dbp", "temperature", "nihss", "pupilExam", "focalDeficit", "creatinine", "inr", "platelets", "imaging"],
    required: ["age", "lastKnownWell", "sbp", "gcs", "nihss", "imaging", "interventionNeeded", "capabilityNeeded"],
  },
  {
    id: "polytrauma.trauma-surgery.v1",
    version: "1.0.0",
    specialty: "Emergência · Cirurgia do Trauma · Ortopedia",
    syndrome: "Politrauma",
    title: "Politrauma com necessidade de centro de trauma",
    purpose: "Organizar mecanismo, fisiologia, hemorragia, imagem e capacidades cirúrgicas necessárias.",
    defaultIntervention: "Controle de hemorragia e tratamento definitivo das lesões tempo-dependentes.",
    defaultCapability: "Centro de trauma com cirurgia, banco de sangue, imagem e UTI; especialidades adicionais conforme lesões.",
    fields: [...common, "symptomOnset", "sbp", "dbp", "temperature", "injuryMechanism", "hemorrhage", "lactate", "ph", "platelets", "inr", "imaging"],
    required: ["age", "symptomOnset", "injuryMechanism", "sbp", "gcs", "hemorrhage", "interventionNeeded", "capabilityNeeded"],
  },
  {
    id: "acute-respiratory-failure.critical-care.v1",
    version: "1.0.0",
    specialty: "Emergência · Pneumologia · Medicina intensiva",
    syndrome: "Insuficiência respiratória aguda",
    title: "Insuficiência respiratória aguda com suporte avançado",
    purpose: "Estruturar gravidade respiratória e necessidade de ventilação avançada/ECMO.",
    defaultIntervention: "Otimização ventilatória e avaliação de suporte extracorpóreo quando clinicamente indicado.",
    defaultCapability: "UTI com ventilação avançada; centro ECMO quando a questão regulatória exigir.",
    fields: [...common, "symptomOnset", "sbp", "dbp", "temperature", "ph", "pao2", "fio2", "lactate", "creatinine", "imaging"],
    required: ["age", "recognitionTime", "spo2", "oxygenSupport", "ph", "pao2", "fio2", "interventionNeeded", "capabilityNeeded"],
  },
  {
    id: "neurosurgical-emergency.neurosurgery.v1",
    version: "1.0.0",
    specialty: "Emergência · Neurocirurgia · Medicina intensiva",
    syndrome: "Emergência neurocirúrgica",
    title: "Emergência neurocirúrgica tempo-dependente",
    purpose: "Estruturar nível de consciência, focalidade, pupilas, imagem e capacidade neurocirúrgica requerida.",
    defaultIntervention: "Avaliação neurocirúrgica e intervenção/descompressão conforme lesão e evolução.",
    defaultCapability: "Neurocirurgia de urgência + neuroimagem + centro cirúrgico e UTI disponíveis.",
    fields: [...common, "symptomOnset", "sbp", "dbp", "temperature", "pupilExam", "focalDeficit", "platelets", "inr", "imaging"],
    required: ["age", "symptomOnset", "gcs", "pupilExam", "focalDeficit", "imaging", "interventionNeeded", "capabilityNeeded"],
  },
]);

export function getSchema(id) {
  return SCHEMA_TEMPLATES.find((schema) => schema.id === id) ?? SCHEMA_TEMPLATES[0];
}

export function getFieldDefinition(key) {
  return FIELD_CATALOG[key] ?? { label: key, type: "text", group: "Outros" };
}
